In [10]:
import tensorflow as tf
from cgcnn.data_tf import CIFData, collate_pool, Dataloader, CIFData_from_DataFrame
from cgcnn.model_tf import CrystalGraphConvNet
import pandas as pd

In [2]:
import functools
import os
import json
import numpy as np
from pymatgen.core.structure import Structure
import math
import warnings

In [27]:
# dataset = CIFData("data/sample-regression/")
df = pd.read_excel("Test-file.xlsx")
df.columns = ["id", "target", "cif"]
dataset = CIFData_from_DataFrame(df.iloc[:100])

In [29]:
structures, _, _ = dataset[0]
orig_atom_fea_len = structures[0].shape[-1]
nbr_fea_len = structures[1].shape[-1]

In [30]:
cgcnn_m = CrystalGraphConvNet(orig_atom_fea_len, nbr_fea_len,
                            atom_fea_len=64,
                            n_conv=3,
                            h_fea_len=128,
                            n_h=1)
cgcnn_m.compile(optimizer='adam', loss='mean_squared_error',metrics=[tf.keras.metrics.RootMeanSquaredError(), 'mae'], run_eagerly=True)

In [35]:
batched = Dataloader(dataset, batch_size=1)

In [36]:
history = cgcnn_m.fit(batched, epochs=1)

100/100 [==============================] - 17s 167ms/step - loss: 1.7008 - root_mean_squared_error: 1.3042 - mae: 1.0422


In [37]:
batched = Dataloader(dataset, batch_size=8)
history = cgcnn_m.fit(batched, epochs=1)

 8/13 [=================>............] - ETA: 1s - loss: 0.9351 - root_mean_squared_error: 0.9670 - mae: 0.7932

InvalidArgumentError: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was ((tf.float64, tf.float64, tf.int32, (tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32)), tf.float32), but the yielded element was ((<tf.Tensor: shape=(102, 92), dtype=float64, numpy=
array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])>, <tf.Tensor: shape=(102, 12, 41), dtype=float64, numpy=
array([[[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       [[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       [[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       ...,

       [[4.16487554e-040, 2.86013919e-032, 2.65817364e-025, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [7.06146417e-044, 1.18198205e-035, 2.67755275e-028, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [2.64705940e-045, 6.14312211e-037, 1.92941497e-029, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [5.08537140e-093, 8.59404847e-081, 1.96554938e-069, ...,
         5.59159615e-239, 9.31172831e-260, 2.09862978e-281],
        [2.52429004e-093, 4.47572437e-081, 1.07398558e-069, ...,
         1.72033381e-238, 3.00577300e-259, 7.10739857e-281],
        [2.60576770e-097, 8.60550083e-085, 3.84616260e-073, ...,
         3.26461064e-232, 1.06240773e-252, 4.67909740e-274]],

       [[5.97101976e-041, 5.02284992e-033, 5.71824726e-026, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [3.53299490e-041, 3.13828588e-033, 3.77270659e-026, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [4.35371700e-047, 1.50951420e-038, 7.08313057e-031, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [3.61722019e-085, 1.72048320e-073, 1.10748274e-062, ...,
         4.75118629e-252, 2.22688057e-273, 1.41254674e-295],
        [3.24203011e-085, 1.55418496e-073, 1.00832235e-062, ...,
         5.73892347e-252, 2.71103713e-273, 1.73321139e-295],
        [5.89309453e-086, 3.19155140e-074, 2.33922133e-063, ...,
         1.07478703e-250, 5.73588226e-272, 4.14275333e-294]],

       [[2.51617759e-042, 2.93323991e-034, 4.62769703e-027, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [9.25993190e-044, 1.50836567e-035, 3.32519045e-028, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [9.50711549e-045, 1.94398769e-036, 5.37959136e-029, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [2.42237091e-084, 1.00494691e-072, 5.64230597e-062, ...,
         1.76397833e-253, 7.21132551e-275, 3.98977118e-297],
        [1.05792258e-084, 4.65862744e-073, 2.77634293e-062, ...,
         7.42964108e-253, 3.22397230e-274, 1.89332777e-296],
        [2.39156034e-085, 1.17175503e-073, 7.76968383e-063, ...,
         9.69500823e-252, 4.68083186e-273, 3.05850318e-295]]])>, <tf.Tensor: shape=(102, 12), dtype=int32, numpy=
array([[ 28,  34,  17, ...,  32,  39,  39],
       [ 35,  29,  14, ...,  31,  38,  38],
       [ 32,  30,  13, ...,  28,  37,  37],
       ...,
       [ 82,  84,  77, ..., 101,  86,  95],
       [ 79,  85,  78, ...,  94,  86,  95],
       [ 83,  80,  84, ...,  97,  94,  98]])>, (<tf.Tensor: shape=(48,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])>, <tf.Tensor: shape=(20,), dtype=int32, numpy=
array([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67])>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([68, 69])>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101])>)), <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.38000348],
       [-2.1561375 ],
       [-0.7611585 ],
       [-1.839548  ]], dtype=float32)>).
Traceback (most recent call last):

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 998, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 385, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 312, in assert_shallow_structure
    assert_shallow_structure(shallow_branch, input_branch,

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 312, in assert_shallow_structure
    assert_shallow_structure(shallow_branch, input_branch,

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 297, in assert_shallow_structure
    raise ValueError(

ValueError: The two structures don't have the same sequence length. Input structure has length 4, while shallow structure has length 8.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 275, in __call__
    ret = func(*args)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 649, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1000, in generator_py_func
    six.reraise(

  File "C:\Users\USER\anaconda3\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 998, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 385, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 312, in assert_shallow_structure
    assert_shallow_structure(shallow_branch, input_branch,

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 312, in assert_shallow_structure
    assert_shallow_structure(shallow_branch, input_branch,

  File "C:\Users\USER\anaconda3\lib\site-packages\tensorflow\python\data\util\nest.py", line 297, in assert_shallow_structure
    raise ValueError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was ((tf.float64, tf.float64, tf.int32, (tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32)), tf.float32), but the yielded element was ((<tf.Tensor: shape=(102, 92), dtype=float64, numpy=
array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])>, <tf.Tensor: shape=(102, 12, 41), dtype=float64, numpy=
array([[[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       [[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       [[1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [1.19050441e-082, 3.72483257e-071, 1.57722460e-060, ...,
         1.91411459e-256, 5.90150879e-278, 2.46246020e-300],
        [5.12098584e-090, 5.36445697e-078, 7.60517118e-067, ...,
         7.20867233e-244, 7.44126639e-265, 1.03955975e-286],
        ...,
        [4.31290519e-095, 1.00915791e-082, 3.19565129e-071, ...,
         1.11152344e-235, 2.56287379e-256, 7.99736372e-278],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270],
        [1.24658589e-099, 5.87792711e-087, 3.75091499e-075, ...,
         1.17694520e-228, 5.46861824e-249, 3.43882446e-270]],

       ...,

       [[4.16487554e-040, 2.86013919e-032, 2.65817364e-025, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [7.06146417e-044, 1.18198205e-035, 2.67755275e-028, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [2.64705940e-045, 6.14312211e-037, 1.92941497e-029, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [5.08537140e-093, 8.59404847e-081, 1.96554938e-069, ...,
         5.59159615e-239, 9.31172831e-260, 2.09862978e-281],
        [2.52429004e-093, 4.47572437e-081, 1.07398558e-069, ...,
         1.72033381e-238, 3.00577300e-259, 7.10739857e-281],
        [2.60576770e-097, 8.60550083e-085, 3.84616260e-073, ...,
         3.26461064e-232, 1.06240773e-252, 4.67909740e-274]],

       [[5.97101976e-041, 5.02284992e-033, 5.71824726e-026, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [3.53299490e-041, 3.13828588e-033, 3.77270659e-026, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [4.35371700e-047, 1.50951420e-038, 7.08313057e-031, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [3.61722019e-085, 1.72048320e-073, 1.10748274e-062, ...,
         4.75118629e-252, 2.22688057e-273, 1.41254674e-295],
        [3.24203011e-085, 1.55418496e-073, 1.00832235e-062, ...,
         5.73892347e-252, 2.71103713e-273, 1.73321139e-295],
        [5.89309453e-086, 3.19155140e-074, 2.33922133e-063, ...,
         1.07478703e-250, 5.73588226e-272, 4.14275333e-294]],

       [[2.51617759e-042, 2.93323991e-034, 4.62769703e-027, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [9.25993190e-044, 1.50836567e-035, 3.32519045e-028, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [9.50711549e-045, 1.94398769e-036, 5.37959136e-029, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        ...,
        [2.42237091e-084, 1.00494691e-072, 5.64230597e-062, ...,
         1.76397833e-253, 7.21132551e-275, 3.98977118e-297],
        [1.05792258e-084, 4.65862744e-073, 2.77634293e-062, ...,
         7.42964108e-253, 3.22397230e-274, 1.89332777e-296],
        [2.39156034e-085, 1.17175503e-073, 7.76968383e-063, ...,
         9.69500823e-252, 4.68083186e-273, 3.05850318e-295]]])>, <tf.Tensor: shape=(102, 12), dtype=int32, numpy=
array([[ 28,  34,  17, ...,  32,  39,  39],
       [ 35,  29,  14, ...,  31,  38,  38],
       [ 32,  30,  13, ...,  28,  37,  37],
       ...,
       [ 82,  84,  77, ..., 101,  86,  95],
       [ 79,  85,  78, ...,  94,  86,  95],
       [ 83,  80,  84, ...,  97,  94,  98]])>, (<tf.Tensor: shape=(48,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])>, <tf.Tensor: shape=(20,), dtype=int32, numpy=
array([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67])>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([68, 69])>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101])>)), <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.38000348],
       [-2.1561375 ],
       [-0.7611585 ],
       [-1.839548  ]], dtype=float32)>).


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]